// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idl/article/article.proto

package article_svc // import "pb/article"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ArticleInfo struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	VisibleType          int32    `protobuf:"varint,4,opt,name=visible_type,json=visibleType" json:"visible_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleInfo) Reset()         { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()    {}
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_439c12d11d385ac7, []int{0}
}
func (m *ArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleInfo.Unmarshal(m, b)
}
func (m *ArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleInfo.Marshal(b, m, deterministic)
}
func (dst *ArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleInfo.Merge(dst, src)
}
func (m *ArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleInfo.Size(m)
}
func (m *ArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleInfo proto.InternalMessageInfo

func (m *ArticleInfo) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *ArticleInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ArticleInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ArticleInfo) GetVisibleType() int32 {
	if m != nil {
		return m.VisibleType
	}
	return 0
}

type ArticleRequest struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleRequest) Reset()         { *m = ArticleRequest{} }
func (m *ArticleRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleRequest) ProtoMessage()    {}
func (*ArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_439c12d11d385ac7, []int{1}
}
func (m *ArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleRequest.Unmarshal(m, b)
}
func (m *ArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleRequest.Marshal(b, m, deterministic)
}
func (dst *ArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleRequest.Merge(dst, src)
}
func (m *ArticleRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleRequest.Size(m)
}
func (m *ArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleRequest proto.InternalMessageInfo

func (m *ArticleRequest) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type ArticleResponse struct {
	ArticleInfo          *ArticleInfo `protobuf:"bytes,1,opt,name=article_info,json=articleInfo" json:"article_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ArticleResponse) Reset()         { *m = ArticleResponse{} }
func (m *ArticleResponse) String() string { return proto.CompactTextString(m) }
func (*ArticleResponse) ProtoMessage()    {}
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_439c12d11d385ac7, []int{2}
}
func (m *ArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleResponse.Unmarshal(m, b)
}
func (m *ArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleResponse.Marshal(b, m, deterministic)
}
func (dst *ArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleResponse.Merge(dst, src)
}
func (m *ArticleResponse) XXX_Size() int {
	return xxx_messageInfo_ArticleResponse.Size(m)
}
func (m *ArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleResponse proto.InternalMessageInfo

func (m *ArticleResponse) GetArticleInfo() *ArticleInfo {
	if m != nil {
		return m.ArticleInfo
	}
	return nil
}

type ArticleBatchRequest struct {
	ArticleIds           []int64  `protobuf:"varint,1,rep,packed,name=article_ids,json=articleIds" json:"article_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleBatchRequest) Reset()         { *m = ArticleBatchRequest{} }
func (m *ArticleBatchRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleBatchRequest) ProtoMessage()    {}
func (*ArticleBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_439c12d11d385ac7, []int{3}
}
func (m *ArticleBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleBatchRequest.Unmarshal(m, b)
}
func (m *ArticleBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleBatchRequest.Marshal(b, m, deterministic)
}
func (dst *ArticleBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleBatchRequest.Merge(dst, src)
}
func (m *ArticleBatchRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleBatchRequest.Size(m)
}
func (m *ArticleBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleBatchRequest proto.InternalMessageInfo

func (m *ArticleBatchRequest) GetArticleIds() []int64 {
	if m != nil {
		return m.ArticleIds
	}
	return nil
}

type ArticleBatchResponse struct {
	ArticleInfos         map[int64]*ArticleInfo `protobuf:"bytes,1,rep,name=article_infos,json=articleInfos" json:"article_infos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ArticleBatchResponse) Reset()         { *m = ArticleBatchResponse{} }
func (m *ArticleBatchResponse) String() string { return proto.CompactTextString(m) }
func (*ArticleBatchResponse) ProtoMessage()    {}
func (*ArticleBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_439c12d11d385ac7, []int{4}
}
func (m *ArticleBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleBatchResponse.Unmarshal(m, b)
}
func (m *ArticleBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleBatchResponse.Marshal(b, m, deterministic)
}
func (dst *ArticleBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleBatchResponse.Merge(dst, src)
}
func (m *ArticleBatchResponse) XXX_Size() int {
	return xxx_messageInfo_ArticleBatchResponse.Size(m)
}
func (m *ArticleBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleBatchResponse proto.InternalMessageInfo

func (m *ArticleBatchResponse) GetArticleInfos() map[int64]*ArticleInfo {
	if m != nil {
		return m.ArticleInfos
	}
	return nil
}

type PublishArticleRequest struct {
	ArticleInfo          *ArticleInfo `protobuf:"bytes,1,opt,name=article_info,json=articleInfo" json:"article_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PublishArticleRequest) Reset()         { *m = PublishArticleRequest{} }
func (m *PublishArticleRequest) String() string { return proto.CompactTextString(m) }
func (*PublishArticleRequest) ProtoMessage()    {}
func (*PublishArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_439c12d11d385ac7, []int{5}
}
func (m *PublishArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishArticleRequest.Unmarshal(m, b)
}
func (m *PublishArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishArticleRequest.Marshal(b, m, deterministic)
}
func (dst *PublishArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishArticleRequest.Merge(dst, src)
}
func (m *PublishArticleRequest) XXX_Size() int {
	return xxx_messageInfo_PublishArticleRequest.Size(m)
}
func (m *PublishArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishArticleRequest proto.InternalMessageInfo

func (m *PublishArticleRequest) GetArticleInfo() *ArticleInfo {
	if m != nil {
		return m.ArticleInfo
	}
	return nil
}

type VisibleTypeRequest struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	VisibleType          int32    `protobuf:"varint,2,opt,name=visible_type,json=visibleType" json:"visible_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisibleTypeRequest) Reset()         { *m = VisibleTypeRequest{} }
func (m *VisibleTypeRequest) String() string { return proto.CompactTextString(m) }
func (*VisibleTypeRequest) ProtoMessage()    {}
func (*VisibleTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_439c12d11d385ac7, []int{6}
}
func (m *VisibleTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisibleTypeRequest.Unmarshal(m, b)
}
func (m *VisibleTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisibleTypeRequest.Marshal(b, m, deterministic)
}
func (dst *VisibleTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisibleTypeRequest.Merge(dst, src)
}
func (m *VisibleTypeRequest) XXX_Size() int {
	return xxx_messageInfo_VisibleTypeRequest.Size(m)
}
func (m *VisibleTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VisibleTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VisibleTypeRequest proto.InternalMessageInfo

func (m *VisibleTypeRequest) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *VisibleTypeRequest) GetVisibleType() int32 {
	if m != nil {
		return m.VisibleType
	}
	return 0
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_439c12d11d385ac7, []int{7}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ArticleInfo)(nil), "article.ArticleInfo")
	proto.RegisterType((*ArticleRequest)(nil), "article.ArticleRequest")
	proto.RegisterType((*ArticleResponse)(nil), "article.ArticleResponse")
	proto.RegisterType((*ArticleBatchRequest)(nil), "article.ArticleBatchRequest")
	proto.RegisterType((*ArticleBatchResponse)(nil), "article.ArticleBatchResponse")
	proto.RegisterMapType((map[int64]*ArticleInfo)(nil), "article.ArticleBatchResponse.ArticleInfosEntry")
	proto.RegisterType((*PublishArticleRequest)(nil), "article.PublishArticleRequest")
	proto.RegisterType((*VisibleTypeRequest)(nil), "article.VisibleTypeRequest")
	proto.RegisterType((*EmptyResponse)(nil), "article.EmptyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Article service

type ArticleClient interface {
	GetArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	GetBatchArticle(ctx context.Context, in *ArticleBatchRequest, opts ...grpc.CallOption) (*ArticleBatchResponse, error)
	ChangeVisibleType(ctx context.Context, in *VisibleTypeRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	PublishArticle(ctx context.Context, in *PublishArticleRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type articleClient struct {
	cc *grpc.ClientConn
}

func NewArticleClient(cc *grpc.ClientConn) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) GetArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	out := new(ArticleResponse)
	err := grpc.Invoke(ctx, "/article.Article/GetArticle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) GetBatchArticle(ctx context.Context, in *ArticleBatchRequest, opts ...grpc.CallOption) (*ArticleBatchResponse, error) {
	out := new(ArticleBatchResponse)
	err := grpc.Invoke(ctx, "/article.Article/GetBatchArticle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) ChangeVisibleType(ctx context.Context, in *VisibleTypeRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/article.Article/ChangeVisibleType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) PublishArticle(ctx context.Context, in *PublishArticleRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/article.Article/PublishArticle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) DeleteArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/article.Article/DeleteArticle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Article service

type ArticleServer interface {
	GetArticle(context.Context, *ArticleRequest) (*ArticleResponse, error)
	GetBatchArticle(context.Context, *ArticleBatchRequest) (*ArticleBatchResponse, error)
	ChangeVisibleType(context.Context, *VisibleTypeRequest) (*EmptyResponse, error)
	PublishArticle(context.Context, *PublishArticleRequest) (*EmptyResponse, error)
	DeleteArticle(context.Context, *ArticleRequest) (*EmptyResponse, error)
}

func RegisterArticleServer(s *grpc.Server, srv ArticleServer) {
	s.RegisterService(&_Article_serviceDesc, srv)
}

func _Article_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/GetArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticle(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_GetBatchArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetBatchArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/GetBatchArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetBatchArticle(ctx, req.(*ArticleBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_ChangeVisibleType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisibleTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).ChangeVisibleType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/ChangeVisibleType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).ChangeVisibleType(ctx, req.(*VisibleTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_PublishArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).PublishArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/PublishArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).PublishArticle(ctx, req.(*PublishArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/DeleteArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).DeleteArticle(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Article_serviceDesc = grpc.ServiceDesc{
	ServiceName: "article.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticle",
			Handler:    _Article_GetArticle_Handler,
		},
		{
			MethodName: "GetBatchArticle",
			Handler:    _Article_GetBatchArticle_Handler,
		},
		{
			MethodName: "ChangeVisibleType",
			Handler:    _Article_ChangeVisibleType_Handler,
		},
		{
			MethodName: "PublishArticle",
			Handler:    _Article_PublishArticle_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _Article_DeleteArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/article/article.proto",
}

func init() { proto.RegisterFile("idl/article/article.proto", fileDescriptor_article_439c12d11d385ac7) }

var fileDescriptor_article_439c12d11d385ac7 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x65, 0x9b, 0x12, 0x75, 0x9c, 0x34, 0x74, 0x29, 0x65, 0x09, 0x14, 0x8c, 0x4f, 0x16,
	0x87, 0x46, 0x0a, 0x12, 0x20, 0x38, 0x00, 0x85, 0xaa, 0x0d, 0x07, 0x14, 0x59, 0x21, 0x07, 0x2e,
	0x91, 0xff, 0x4c, 0x88, 0x85, 0xb1, 0x4d, 0x76, 0x1d, 0xc9, 0xe2, 0xf1, 0x78, 0x21, 0x1e, 0x01,
	0xc5, 0xde, 0x75, 0xec, 0x18, 0x13, 0xc4, 0xc9, 0x3b, 0x3b, 0xfb, 0x8d, 0xbf, 0x99, 0xdf, 0x6a,
	0xe1, 0x5e, 0xe0, 0x87, 0x43, 0x67, 0xc5, 0x03, 0x2f, 0x44, 0xf9, 0x3d, 0x4f, 0x56, 0x31, 0x8f,
	0x49, 0x47, 0x84, 0xe6, 0x0f, 0xd0, 0xdf, 0x16, 0xcb, 0x71, 0xb4, 0x88, 0xc9, 0x19, 0x80, 0xc8,
	0xcc, 0x03, 0x9f, 0x2a, 0x86, 0x62, 0x69, 0xf6, 0xa1, 0xd8, 0x19, 0xfb, 0xe4, 0x16, 0x68, 0x69,
	0xe0, 0x53, 0x35, 0xdf, 0xdf, 0x2c, 0x09, 0x85, 0x8e, 0x17, 0x47, 0x1c, 0x23, 0x4e, 0x35, 0x43,
	0xb1, 0x0e, 0x6d, 0x19, 0x92, 0xc7, 0xd0, 0x5d, 0x07, 0x2c, 0x70, 0x43, 0x9c, 0xf3, 0x2c, 0x41,
	0x7a, 0xc3, 0x50, 0xac, 0x03, 0x5b, 0x17, 0x7b, 0xd3, 0x2c, 0x41, 0x73, 0x08, 0x47, 0xe2, 0xe7,
	0x36, 0x7e, 0x4f, 0x91, 0xf1, 0x3d, 0xff, 0x37, 0x3f, 0x40, 0xbf, 0x14, 0xb0, 0x24, 0x8e, 0x18,
	0x92, 0xe7, 0xd0, 0x2d, 0x15, 0xd1, 0x22, 0xce, 0x35, 0xfa, 0xe8, 0xe4, 0x5c, 0xf6, 0x5b, 0xe9,
	0xce, 0xd6, 0x9d, 0x6d, 0x60, 0x3e, 0x83, 0xdb, 0x22, 0x77, 0xe1, 0x70, 0x6f, 0x29, 0x1d, 0x3c,
	0x02, 0x7d, 0xeb, 0x80, 0x51, 0xc5, 0xd0, 0x2c, 0xcd, 0x86, 0xd2, 0x02, 0x33, 0x7f, 0x2a, 0x70,
	0x52, 0x17, 0x0a, 0x27, 0x53, 0xe8, 0x55, 0x9d, 0x14, 0x5a, 0x7d, 0x34, 0xdc, 0xb5, 0x52, 0x53,
	0x55, 0xfd, 0xb1, 0xcb, 0x88, 0xaf, 0x32, 0xbb, 0x5b, 0x71, 0xc9, 0x06, 0x9f, 0xe0, 0xb8, 0x71,
	0x64, 0xc3, 0xe1, 0x2b, 0x66, 0x62, 0x3e, 0x9b, 0x25, 0x79, 0x02, 0x07, 0x6b, 0x27, 0x4c, 0x31,
	0x67, 0xd3, 0xd6, 0x7f, 0x71, 0xe4, 0xa5, 0xfa, 0x42, 0x31, 0x27, 0x70, 0x67, 0x92, 0xba, 0x61,
	0xc0, 0x96, 0x3b, 0x04, 0xfe, 0x7b, 0x9e, 0x33, 0x20, 0xb3, 0x2d, 0xdb, 0x7f, 0x03, 0xda, 0xb8,
	0x24, 0x6a, 0xf3, 0x92, 0xf4, 0xa1, 0x77, 0xf9, 0x2d, 0xe1, 0x99, 0x9c, 0xd8, 0xe8, 0x97, 0x0a,
	0x1d, 0xe1, 0x82, 0xbc, 0x06, 0xb8, 0x42, 0x2e, 0xa3, 0xbb, 0xbb, 0x2e, 0x85, 0x8b, 0x01, 0x6d,
	0x26, 0x04, 0xb4, 0x8f, 0xd0, 0xbf, 0x42, 0x9e, 0x23, 0x91, 0x55, 0x1e, 0xb4, 0x00, 0x2b, 0x4a,
	0x9d, 0xfd, 0x15, 0x27, 0xb9, 0x86, 0xe3, 0x77, 0x4b, 0x27, 0xfa, 0x82, 0x95, 0x59, 0x90, 0xfb,
	0xa5, 0xa6, 0x39, 0xa1, 0xc1, 0x69, 0x99, 0xac, 0xb5, 0x49, 0xae, 0xe1, 0xa8, 0x4e, 0x88, 0x3c,
	0x2c, 0x4f, 0xfe, 0x11, 0x5d, 0x6b, 0xa5, 0x37, 0xd0, 0x7b, 0x8f, 0x21, 0x72, 0xdc, 0x3b, 0xa7,
	0x96, 0x0a, 0x17, 0xf4, 0xf3, 0x69, 0xe2, 0xca, 0x27, 0xe4, 0x95, 0x04, 0xca, 0xd6, 0x9e, 0x7b,
	0x33, 0x7f, 0x4f, 0x9e, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x44, 0xe8, 0x2b, 0x97, 0x6c, 0x04,
	0x00, 0x00,
}
