// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idl/user/user.proto

package user_svc // import "pb/user"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender" json:"gender,omitempty"`
	Introduction         string   `protobuf:"bytes,4,opt,name=introduction" json:"introduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{0}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (dst *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(dst, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserInfo) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

type UserInfoRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{1}
}
func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(dst, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserInfoResponse struct {
	Userinfo             *UserInfo `protobuf:"bytes,1,opt,name=userinfo" json:"userinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{2}
}
func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (dst *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(dst, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetUserinfo() *UserInfo {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

type UserInfoBatchRequest struct {
	Uids                 []int64  `protobuf:"varint,1,rep,packed,name=uids" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoBatchRequest) Reset()         { *m = UserInfoBatchRequest{} }
func (m *UserInfoBatchRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoBatchRequest) ProtoMessage()    {}
func (*UserInfoBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{3}
}
func (m *UserInfoBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoBatchRequest.Unmarshal(m, b)
}
func (m *UserInfoBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoBatchRequest.Marshal(b, m, deterministic)
}
func (dst *UserInfoBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoBatchRequest.Merge(dst, src)
}
func (m *UserInfoBatchRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoBatchRequest.Size(m)
}
func (m *UserInfoBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoBatchRequest proto.InternalMessageInfo

func (m *UserInfoBatchRequest) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

type UserInfoBatchResponse struct {
	Userinfos            map[int64]*UserInfo `protobuf:"bytes,1,rep,name=userinfos" json:"userinfos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserInfoBatchResponse) Reset()         { *m = UserInfoBatchResponse{} }
func (m *UserInfoBatchResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoBatchResponse) ProtoMessage()    {}
func (*UserInfoBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{4}
}
func (m *UserInfoBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoBatchResponse.Unmarshal(m, b)
}
func (m *UserInfoBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoBatchResponse.Marshal(b, m, deterministic)
}
func (dst *UserInfoBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoBatchResponse.Merge(dst, src)
}
func (m *UserInfoBatchResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoBatchResponse.Size(m)
}
func (m *UserInfoBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoBatchResponse proto.InternalMessageInfo

func (m *UserInfoBatchResponse) GetUserinfos() map[int64]*UserInfo {
	if m != nil {
		return m.Userinfos
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{5}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type RelationInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	ToUid                int64    `protobuf:"varint,2,opt,name=to_uid,json=toUid" json:"to_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationInfo) Reset()         { *m = RelationInfo{} }
func (m *RelationInfo) String() string { return proto.CompactTextString(m) }
func (*RelationInfo) ProtoMessage()    {}
func (*RelationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{6}
}
func (m *RelationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationInfo.Unmarshal(m, b)
}
func (m *RelationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationInfo.Marshal(b, m, deterministic)
}
func (dst *RelationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationInfo.Merge(dst, src)
}
func (m *RelationInfo) XXX_Size() int {
	return xxx_messageInfo_RelationInfo.Size(m)
}
func (m *RelationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RelationInfo proto.InternalMessageInfo

func (m *RelationInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RelationInfo) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

type CollectionRequest struct {
	CollectionInfo       *RelationInfo `protobuf:"bytes,1,opt,name=collection_info,json=collectionInfo" json:"collection_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CollectionRequest) Reset()         { *m = CollectionRequest{} }
func (m *CollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionRequest) ProtoMessage()    {}
func (*CollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{7}
}
func (m *CollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionRequest.Unmarshal(m, b)
}
func (m *CollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionRequest.Marshal(b, m, deterministic)
}
func (dst *CollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionRequest.Merge(dst, src)
}
func (m *CollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionRequest.Size(m)
}
func (m *CollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionRequest proto.InternalMessageInfo

func (m *CollectionRequest) GetCollectionInfo() *RelationInfo {
	if m != nil {
		return m.CollectionInfo
	}
	return nil
}

type AddBrowseRequest struct {
	BrowseInfo           *RelationInfo `protobuf:"bytes,1,opt,name=browse_info,json=browseInfo" json:"browse_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddBrowseRequest) Reset()         { *m = AddBrowseRequest{} }
func (m *AddBrowseRequest) String() string { return proto.CompactTextString(m) }
func (*AddBrowseRequest) ProtoMessage()    {}
func (*AddBrowseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{8}
}
func (m *AddBrowseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBrowseRequest.Unmarshal(m, b)
}
func (m *AddBrowseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBrowseRequest.Marshal(b, m, deterministic)
}
func (dst *AddBrowseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBrowseRequest.Merge(dst, src)
}
func (m *AddBrowseRequest) XXX_Size() int {
	return xxx_messageInfo_AddBrowseRequest.Size(m)
}
func (m *AddBrowseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBrowseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBrowseRequest proto.InternalMessageInfo

func (m *AddBrowseRequest) GetBrowseInfo() *RelationInfo {
	if m != nil {
		return m.BrowseInfo
	}
	return nil
}

type CreateUserRequest struct {
	Userinfo             *UserInfo `protobuf:"bytes,1,opt,name=userinfo" json:"userinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{9}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUserinfo() *UserInfo {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

type ListRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Cursor               int64    `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{10}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ListRequest) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListResponse struct {
	TargetIds            []int64  `protobuf:"varint,1,rep,packed,name=target_ids,json=targetIds" json:"target_ids,omitempty"`
	NextCursor           int64    `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor" json:"next_cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_468a7a182a8f89c0, []int{11}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetTargetIds() []int64 {
	if m != nil {
		return m.TargetIds
	}
	return nil
}

func (m *ListResponse) GetNextCursor() int64 {
	if m != nil {
		return m.NextCursor
	}
	return 0
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*UserInfoRequest)(nil), "user.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "user.UserInfoResponse")
	proto.RegisterType((*UserInfoBatchRequest)(nil), "user.UserInfoBatchRequest")
	proto.RegisterType((*UserInfoBatchResponse)(nil), "user.UserInfoBatchResponse")
	proto.RegisterMapType((map[int64]*UserInfo)(nil), "user.UserInfoBatchResponse.UserinfosEntry")
	proto.RegisterType((*EmptyResponse)(nil), "user.EmptyResponse")
	proto.RegisterType((*RelationInfo)(nil), "user.RelationInfo")
	proto.RegisterType((*CollectionRequest)(nil), "user.CollectionRequest")
	proto.RegisterType((*AddBrowseRequest)(nil), "user.AddBrowseRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*ListRequest)(nil), "user.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "user.ListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	GetUserinfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	GetBatchUserinfo(ctx context.Context, in *UserInfoBatchRequest, opts ...grpc.CallOption) (*UserInfoBatchResponse, error)
	GetHistoryBrowse(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetCollectionList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Collection(ctx context.Context, in *CollectionRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	CancelCollection(ctx context.Context, in *CollectionRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	AddBrowse(ctx context.Context, in *AddBrowseRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserinfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := grpc.Invoke(ctx, "/user.User/GetUserinfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetBatchUserinfo(ctx context.Context, in *UserInfoBatchRequest, opts ...grpc.CallOption) (*UserInfoBatchResponse, error) {
	out := new(UserInfoBatchResponse)
	err := grpc.Invoke(ctx, "/user.User/GetBatchUserinfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetHistoryBrowse(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/user.User/GetHistoryBrowse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetCollectionList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/user.User/GetCollectionList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Collection(ctx context.Context, in *CollectionRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/user.User/Collection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CancelCollection(ctx context.Context, in *CollectionRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/user.User/CancelCollection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddBrowse(ctx context.Context, in *AddBrowseRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/user.User/AddBrowse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/user.User/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	GetUserinfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error)
	GetBatchUserinfo(context.Context, *UserInfoBatchRequest) (*UserInfoBatchResponse, error)
	GetHistoryBrowse(context.Context, *ListRequest) (*ListResponse, error)
	GetCollectionList(context.Context, *ListRequest) (*ListResponse, error)
	Collection(context.Context, *CollectionRequest) (*EmptyResponse, error)
	CancelCollection(context.Context, *CollectionRequest) (*EmptyResponse, error)
	AddBrowse(context.Context, *AddBrowseRequest) (*EmptyResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*EmptyResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserinfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserinfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetUserinfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserinfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetBatchUserinfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetBatchUserinfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetBatchUserinfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetBatchUserinfo(ctx, req.(*UserInfoBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetHistoryBrowse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetHistoryBrowse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetHistoryBrowse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetHistoryBrowse(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetCollectionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCollectionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetCollectionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCollectionList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Collection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Collection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Collection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Collection(ctx, req.(*CollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CancelCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CancelCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/CancelCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CancelCollection(ctx, req.(*CollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddBrowse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBrowseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddBrowse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/AddBrowse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddBrowse(ctx, req.(*AddBrowseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserinfo",
			Handler:    _User_GetUserinfo_Handler,
		},
		{
			MethodName: "GetBatchUserinfo",
			Handler:    _User_GetBatchUserinfo_Handler,
		},
		{
			MethodName: "GetHistoryBrowse",
			Handler:    _User_GetHistoryBrowse_Handler,
		},
		{
			MethodName: "GetCollectionList",
			Handler:    _User_GetCollectionList_Handler,
		},
		{
			MethodName: "Collection",
			Handler:    _User_Collection_Handler,
		},
		{
			MethodName: "CancelCollection",
			Handler:    _User_CancelCollection_Handler,
		},
		{
			MethodName: "AddBrowse",
			Handler:    _User_AddBrowse_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/user/user.proto",
}

func init() { proto.RegisterFile("idl/user/user.proto", fileDescriptor_user_468a7a182a8f89c0) }

var fileDescriptor_user_468a7a182a8f89c0 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6f, 0xda, 0x4e,
	0x10, 0x95, 0x63, 0x82, 0x60, 0xcc, 0x0f, 0xcc, 0xe6, 0x47, 0x8a, 0x5c, 0x55, 0x45, 0x6e, 0x0f,
	0x88, 0x43, 0x2a, 0x91, 0x43, 0xd3, 0xa4, 0xea, 0x07, 0x28, 0x22, 0x51, 0xa3, 0xb6, 0xb2, 0x94,
	0x4b, 0x2f, 0xc8, 0xd8, 0x4b, 0x6a, 0xe1, 0xec, 0xd2, 0xdd, 0x75, 0x5a, 0xfe, 0xaa, 0xfe, 0x83,
	0x3d, 0x54, 0xbb, 0xeb, 0x0f, 0x0c, 0xa4, 0x5f, 0x17, 0x6b, 0xf7, 0xcd, 0xcc, 0x7b, 0x33, 0xb3,
	0x4f, 0x86, 0x83, 0x28, 0x8c, 0x9f, 0x25, 0x1c, 0x33, 0xf5, 0x39, 0x5a, 0x32, 0x2a, 0x28, 0xaa,
	0xc8, 0xb3, 0x2b, 0xa0, 0x76, 0xcd, 0x31, 0xbb, 0x24, 0x73, 0x8a, 0x6c, 0x30, 0x93, 0x28, 0xec,
	0x1a, 0x3d, 0xa3, 0x6f, 0x7a, 0xf2, 0x88, 0x1c, 0xa8, 0x91, 0x28, 0x58, 0x10, 0xff, 0x16, 0x77,
	0xf7, 0x7a, 0x46, 0xbf, 0xee, 0xe5, 0x77, 0x74, 0x08, 0xd5, 0x1b, 0x4c, 0x42, 0xcc, 0xba, 0x66,
	0xcf, 0xe8, 0xef, 0x7b, 0xe9, 0x0d, 0xb9, 0xd0, 0x88, 0x88, 0x60, 0x34, 0x4c, 0x02, 0x11, 0x51,
	0xd2, 0xad, 0xa8, 0xba, 0x12, 0xe6, 0x3e, 0x81, 0x56, 0xa6, 0xea, 0xe1, 0x2f, 0x09, 0xe6, 0x62,
	0x5b, 0xdc, 0x7d, 0x05, 0x76, 0x91, 0xc4, 0x97, 0x94, 0x70, 0x8c, 0x06, 0x50, 0x93, 0x6d, 0x47,
	0x64, 0x4e, 0x55, 0xaa, 0x35, 0x6c, 0x1e, 0xa9, 0x99, 0xf2, 0xcc, 0x3c, 0xee, 0x0e, 0xe0, 0xff,
	0x0c, 0x1d, 0xf9, 0x22, 0xf8, 0x9c, 0x29, 0x21, 0xa8, 0x24, 0x51, 0xc8, 0xbb, 0x46, 0xcf, 0xec,
	0x9b, 0x9e, 0x3a, 0xbb, 0xdf, 0x0d, 0xe8, 0x6c, 0x24, 0xa7, 0x8a, 0x17, 0x50, 0xcf, 0x18, 0x75,
	0x89, 0x35, 0x1c, 0x94, 0x25, 0x4b, 0xf9, 0x0a, 0x55, 0xc9, 0xe7, 0x44, 0xb0, 0x95, 0x57, 0x14,
	0x3b, 0x57, 0xd0, 0x2c, 0x07, 0xe5, 0xcc, 0x0b, 0xbc, 0xca, 0x66, 0x5e, 0xe0, 0x15, 0x7a, 0x0a,
	0xfb, 0x77, 0x7e, 0x9c, 0xe8, 0x6d, 0x6f, 0x0f, 0xa7, 0x83, 0xa7, 0x7b, 0x27, 0x86, 0xdb, 0x82,
	0xff, 0xce, 0x6f, 0x97, 0x62, 0x95, 0x09, 0xbb, 0xcf, 0xa1, 0xe1, 0xe1, 0xd8, 0x97, 0xfb, 0xbd,
	0xe7, 0x35, 0x3b, 0x50, 0x15, 0x74, 0x2a, 0xc1, 0x3d, 0x05, 0xee, 0x0b, 0x7a, 0x1d, 0x85, 0xee,
	0x47, 0x68, 0x8f, 0x69, 0x1c, 0x63, 0xf5, 0x34, 0xd9, 0x92, 0xce, 0xa0, 0x15, 0xe4, 0xe0, 0x74,
	0x6d, 0xdf, 0x48, 0xb7, 0xb4, 0x2e, 0xe5, 0x35, 0x8b, 0x54, 0x79, 0x77, 0x27, 0x60, 0xbf, 0x0d,
	0xc3, 0x11, 0xa3, 0x5f, 0x39, 0xce, 0x08, 0x8f, 0xc1, 0x9a, 0x29, 0xe0, 0x77, 0x64, 0xa0, 0xd3,
	0x14, 0xd1, 0x6b, 0x68, 0x8f, 0x19, 0xf6, 0x05, 0x96, 0x1b, 0xc8, 0x98, 0xfe, 0xc6, 0x03, 0x1f,
	0xc0, 0xba, 0x8a, 0xb8, 0xb8, 0xd7, 0x64, 0xd2, 0xc5, 0x41, 0xc2, 0x38, 0x65, 0xe9, 0x4e, 0xd2,
	0x9b, 0xc4, 0xe9, 0x7c, 0xce, 0xb1, 0x50, 0xee, 0x36, 0xbd, 0xf4, 0xe6, 0xbe, 0x87, 0x86, 0x26,
	0x4c, 0xed, 0xf1, 0x08, 0x40, 0xf8, 0xec, 0x06, 0x8b, 0x69, 0x61, 0xa9, 0xba, 0x46, 0x2e, 0x43,
	0x8e, 0x1e, 0x83, 0x45, 0xf0, 0x37, 0x31, 0x2d, 0x69, 0x80, 0x84, 0xc6, 0x0a, 0x19, 0xfe, 0x30,
	0xa1, 0x22, 0xfb, 0x46, 0x2f, 0xc1, 0x9a, 0x60, 0x91, 0x19, 0x04, 0x75, 0x36, 0x46, 0xd2, 0x03,
	0x38, 0x87, 0x9b, 0x70, 0xda, 0xc6, 0x3b, 0xb0, 0x27, 0x58, 0x28, 0x27, 0xe6, 0x14, 0xce, 0x4e,
	0x9b, 0x6a, 0x9e, 0x87, 0xbf, 0xb0, 0x30, 0x7a, 0xa1, 0xc8, 0x2e, 0x22, 0x2e, 0x28, 0x5b, 0xe9,
	0x57, 0x44, 0x6d, 0x5d, 0xb0, 0xb6, 0x4c, 0x07, 0xad, 0x43, 0x69, 0xe9, 0x29, 0xb4, 0x27, 0x58,
	0x14, 0x76, 0x92, 0xc1, 0x3f, 0xaf, 0x85, 0xa2, 0x10, 0x3d, 0xd0, 0x19, 0x5b, 0xce, 0x74, 0x0e,
	0x74, 0xa0, 0x64, 0x7e, 0xf4, 0x06, 0xec, 0xb1, 0x4f, 0x02, 0x1c, 0xff, 0x33, 0xc3, 0x09, 0xd4,
	0x73, 0xcf, 0xa2, 0x74, 0xcd, 0x9b, 0x26, 0xde, 0x5d, 0x29, 0xfb, 0xce, 0x4d, 0x9a, 0xab, 0x6e,
	0xda, 0x76, 0x67, 0xed, 0x08, 0x7d, 0xb2, 0x97, 0x33, 0xf5, 0x57, 0x3e, 0x93, 0x9f, 0x29, 0xbf,
	0x0b, 0x66, 0x55, 0xf5, 0x7f, 0x3e, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0x32, 0x09, 0x27, 0x73,
	0xb6, 0x05, 0x00, 0x00,
}
