// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idl/social/social.proto

package social_svc // import "pb/social"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RelationItem struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	ToUid                int64    `protobuf:"varint,2,opt,name=to_uid,json=toUid" json:"to_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationItem) Reset()         { *m = RelationItem{} }
func (m *RelationItem) String() string { return proto.CompactTextString(m) }
func (*RelationItem) ProtoMessage()    {}
func (*RelationItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{0}
}
func (m *RelationItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationItem.Unmarshal(m, b)
}
func (m *RelationItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationItem.Marshal(b, m, deterministic)
}
func (dst *RelationItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationItem.Merge(dst, src)
}
func (m *RelationItem) XXX_Size() int {
	return xxx_messageInfo_RelationItem.Size(m)
}
func (m *RelationItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationItem.DiscardUnknown(m)
}

var xxx_messageInfo_RelationItem proto.InternalMessageInfo

func (m *RelationItem) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RelationItem) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

type FollowRequest struct {
	FollowItem           *RelationItem `protobuf:"bytes,1,opt,name=follow_item,json=followItem" json:"follow_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FollowRequest) Reset()         { *m = FollowRequest{} }
func (m *FollowRequest) String() string { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()    {}
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{1}
}
func (m *FollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRequest.Unmarshal(m, b)
}
func (m *FollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRequest.Marshal(b, m, deterministic)
}
func (dst *FollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRequest.Merge(dst, src)
}
func (m *FollowRequest) XXX_Size() int {
	return xxx_messageInfo_FollowRequest.Size(m)
}
func (m *FollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRequest proto.InternalMessageInfo

func (m *FollowRequest) GetFollowItem() *RelationItem {
	if m != nil {
		return m.FollowItem
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{2}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type UnfollowRequest struct {
	FollowItem           *RelationItem `protobuf:"bytes,1,opt,name=follow_item,json=followItem" json:"follow_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnfollowRequest) Reset()         { *m = UnfollowRequest{} }
func (m *UnfollowRequest) String() string { return proto.CompactTextString(m) }
func (*UnfollowRequest) ProtoMessage()    {}
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{3}
}
func (m *UnfollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfollowRequest.Unmarshal(m, b)
}
func (m *UnfollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfollowRequest.Marshal(b, m, deterministic)
}
func (dst *UnfollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfollowRequest.Merge(dst, src)
}
func (m *UnfollowRequest) XXX_Size() int {
	return xxx_messageInfo_UnfollowRequest.Size(m)
}
func (m *UnfollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnfollowRequest proto.InternalMessageInfo

func (m *UnfollowRequest) GetFollowItem() *RelationItem {
	if m != nil {
		return m.FollowItem
	}
	return nil
}

type BlackRequest struct {
	BlackItem            *RelationItem `protobuf:"bytes,1,opt,name=black_item,json=blackItem" json:"black_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BlackRequest) Reset()         { *m = BlackRequest{} }
func (m *BlackRequest) String() string { return proto.CompactTextString(m) }
func (*BlackRequest) ProtoMessage()    {}
func (*BlackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{4}
}
func (m *BlackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlackRequest.Unmarshal(m, b)
}
func (m *BlackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlackRequest.Marshal(b, m, deterministic)
}
func (dst *BlackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlackRequest.Merge(dst, src)
}
func (m *BlackRequest) XXX_Size() int {
	return xxx_messageInfo_BlackRequest.Size(m)
}
func (m *BlackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlackRequest proto.InternalMessageInfo

func (m *BlackRequest) GetBlackItem() *RelationItem {
	if m != nil {
		return m.BlackItem
	}
	return nil
}

type BlackResponse struct {
	IsBlack              bool     `protobuf:"varint,1,opt,name=is_black,json=isBlack" json:"is_black,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlackResponse) Reset()         { *m = BlackResponse{} }
func (m *BlackResponse) String() string { return proto.CompactTextString(m) }
func (*BlackResponse) ProtoMessage()    {}
func (*BlackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{5}
}
func (m *BlackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlackResponse.Unmarshal(m, b)
}
func (m *BlackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlackResponse.Marshal(b, m, deterministic)
}
func (dst *BlackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlackResponse.Merge(dst, src)
}
func (m *BlackResponse) XXX_Size() int {
	return xxx_messageInfo_BlackResponse.Size(m)
}
func (m *BlackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlackResponse proto.InternalMessageInfo

func (m *BlackResponse) GetIsBlack() bool {
	if m != nil {
		return m.IsBlack
	}
	return false
}

type ListRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Cursor               int64    `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{6}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ListRequest) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListResponse struct {
	Uids                 []int64  `protobuf:"varint,1,rep,packed,name=uids" json:"uids,omitempty"`
	NextCursor           int64    `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor" json:"next_cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{7}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *ListResponse) GetNextCursor() int64 {
	if m != nil {
		return m.NextCursor
	}
	return 0
}

type CountRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountRequest) Reset()         { *m = CountRequest{} }
func (m *CountRequest) String() string { return proto.CompactTextString(m) }
func (*CountRequest) ProtoMessage()    {}
func (*CountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{8}
}
func (m *CountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountRequest.Unmarshal(m, b)
}
func (m *CountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountRequest.Marshal(b, m, deterministic)
}
func (dst *CountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountRequest.Merge(dst, src)
}
func (m *CountRequest) XXX_Size() int {
	return xxx_messageInfo_CountRequest.Size(m)
}
func (m *CountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountRequest proto.InternalMessageInfo

func (m *CountRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type CountResponse struct {
	FollowCount          int64    `protobuf:"varint,1,opt,name=follow_count,json=followCount" json:"follow_count,omitempty"`
	FollowerCount        int64    `protobuf:"varint,2,opt,name=follower_count,json=followerCount" json:"follower_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{9}
}
func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (dst *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(dst, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetFollowCount() int64 {
	if m != nil {
		return m.FollowCount
	}
	return 0
}

func (m *CountResponse) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

type RelationRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Uids                 []int64  `protobuf:"varint,2,rep,packed,name=uids" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationRequest) Reset()         { *m = RelationRequest{} }
func (m *RelationRequest) String() string { return proto.CompactTextString(m) }
func (*RelationRequest) ProtoMessage()    {}
func (*RelationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{10}
}
func (m *RelationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationRequest.Unmarshal(m, b)
}
func (m *RelationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationRequest.Marshal(b, m, deterministic)
}
func (dst *RelationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationRequest.Merge(dst, src)
}
func (m *RelationRequest) XXX_Size() int {
	return xxx_messageInfo_RelationRequest.Size(m)
}
func (m *RelationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RelationRequest proto.InternalMessageInfo

func (m *RelationRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RelationRequest) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

type RelationResponse struct {
	Relation             map[int64]int32 `protobuf:"bytes,1,rep,name=relation" json:"relation,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RelationResponse) Reset()         { *m = RelationResponse{} }
func (m *RelationResponse) String() string { return proto.CompactTextString(m) }
func (*RelationResponse) ProtoMessage()    {}
func (*RelationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{11}
}
func (m *RelationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationResponse.Unmarshal(m, b)
}
func (m *RelationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationResponse.Marshal(b, m, deterministic)
}
func (dst *RelationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationResponse.Merge(dst, src)
}
func (m *RelationResponse) XXX_Size() int {
	return xxx_messageInfo_RelationResponse.Size(m)
}
func (m *RelationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RelationResponse proto.InternalMessageInfo

func (m *RelationResponse) GetRelation() map[int64]int32 {
	if m != nil {
		return m.Relation
	}
	return nil
}

type BlackBatchResponse struct {
	Relation             map[int64]bool `protobuf:"bytes,1,rep,name=relation" json:"relation,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlackBatchResponse) Reset()         { *m = BlackBatchResponse{} }
func (m *BlackBatchResponse) String() string { return proto.CompactTextString(m) }
func (*BlackBatchResponse) ProtoMessage()    {}
func (*BlackBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_7202e7a91a160a8b, []int{12}
}
func (m *BlackBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlackBatchResponse.Unmarshal(m, b)
}
func (m *BlackBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlackBatchResponse.Marshal(b, m, deterministic)
}
func (dst *BlackBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlackBatchResponse.Merge(dst, src)
}
func (m *BlackBatchResponse) XXX_Size() int {
	return xxx_messageInfo_BlackBatchResponse.Size(m)
}
func (m *BlackBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlackBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlackBatchResponse proto.InternalMessageInfo

func (m *BlackBatchResponse) GetRelation() map[int64]bool {
	if m != nil {
		return m.Relation
	}
	return nil
}

func init() {
	proto.RegisterType((*RelationItem)(nil), "social.RelationItem")
	proto.RegisterType((*FollowRequest)(nil), "social.FollowRequest")
	proto.RegisterType((*EmptyResponse)(nil), "social.EmptyResponse")
	proto.RegisterType((*UnfollowRequest)(nil), "social.UnfollowRequest")
	proto.RegisterType((*BlackRequest)(nil), "social.BlackRequest")
	proto.RegisterType((*BlackResponse)(nil), "social.BlackResponse")
	proto.RegisterType((*ListRequest)(nil), "social.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "social.ListResponse")
	proto.RegisterType((*CountRequest)(nil), "social.CountRequest")
	proto.RegisterType((*CountResponse)(nil), "social.CountResponse")
	proto.RegisterType((*RelationRequest)(nil), "social.RelationRequest")
	proto.RegisterType((*RelationResponse)(nil), "social.RelationResponse")
	proto.RegisterMapType((map[int64]int32)(nil), "social.RelationResponse.RelationEntry")
	proto.RegisterType((*BlackBatchResponse)(nil), "social.BlackBatchResponse")
	proto.RegisterMapType((map[int64]bool)(nil), "social.BlackBatchResponse.RelationEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Social service

type SocialClient interface {
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Unfollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetFollow(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetFollower(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetFollowCount(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error)
	GetRelations(ctx context.Context, in *RelationRequest, opts ...grpc.CallOption) (*RelationResponse, error)
	Black(ctx context.Context, in *BlackRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	CancelBlack(ctx context.Context, in *BlackRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	CheckBlack(ctx context.Context, in *BlackRequest, opts ...grpc.CallOption) (*BlackResponse, error)
	CheckBatchBlack(ctx context.Context, in *RelationRequest, opts ...grpc.CallOption) (*BlackBatchResponse, error)
	GetBlackList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type socialClient struct {
	cc *grpc.ClientConn
}

func NewSocialClient(cc *grpc.ClientConn) SocialClient {
	return &socialClient{cc}
}

func (c *socialClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/social.Social/Follow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) Unfollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/social.Social/Unfollow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetFollow(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/social.Social/GetFollow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetFollower(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/social.Social/GetFollower", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetFollowCount(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := grpc.Invoke(ctx, "/social.Social/GetFollowCount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetRelations(ctx context.Context, in *RelationRequest, opts ...grpc.CallOption) (*RelationResponse, error) {
	out := new(RelationResponse)
	err := grpc.Invoke(ctx, "/social.Social/GetRelations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) Black(ctx context.Context, in *BlackRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/social.Social/Black", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) CancelBlack(ctx context.Context, in *BlackRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/social.Social/CancelBlack", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) CheckBlack(ctx context.Context, in *BlackRequest, opts ...grpc.CallOption) (*BlackResponse, error) {
	out := new(BlackResponse)
	err := grpc.Invoke(ctx, "/social.Social/CheckBlack", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) CheckBatchBlack(ctx context.Context, in *RelationRequest, opts ...grpc.CallOption) (*BlackBatchResponse, error) {
	out := new(BlackBatchResponse)
	err := grpc.Invoke(ctx, "/social.Social/CheckBatchBlack", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetBlackList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/social.Social/GetBlackList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Social service

type SocialServer interface {
	Follow(context.Context, *FollowRequest) (*EmptyResponse, error)
	Unfollow(context.Context, *FollowRequest) (*EmptyResponse, error)
	GetFollow(context.Context, *ListRequest) (*ListResponse, error)
	GetFollower(context.Context, *ListRequest) (*ListResponse, error)
	GetFollowCount(context.Context, *CountRequest) (*CountResponse, error)
	GetRelations(context.Context, *RelationRequest) (*RelationResponse, error)
	Black(context.Context, *BlackRequest) (*EmptyResponse, error)
	CancelBlack(context.Context, *BlackRequest) (*EmptyResponse, error)
	CheckBlack(context.Context, *BlackRequest) (*BlackResponse, error)
	CheckBatchBlack(context.Context, *RelationRequest) (*BlackBatchResponse, error)
	GetBlackList(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterSocialServer(s *grpc.Server, srv SocialServer) {
	s.RegisterService(&_Social_serviceDesc, srv)
}

func _Social_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/Follow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_Unfollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).Unfollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/Unfollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).Unfollow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/GetFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetFollow(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetFollower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetFollower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/GetFollower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetFollower(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetFollowCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetFollowCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/GetFollowCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetFollowCount(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/GetRelations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetRelations(ctx, req.(*RelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_Black_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).Black(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/Black",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).Black(ctx, req.(*BlackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_CancelBlack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).CancelBlack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/CancelBlack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).CancelBlack(ctx, req.(*BlackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_CheckBlack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).CheckBlack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/CheckBlack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).CheckBlack(ctx, req.(*BlackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_CheckBatchBlack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).CheckBatchBlack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/CheckBatchBlack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).CheckBatchBlack(ctx, req.(*RelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/social.Social/GetBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetBlackList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Social_serviceDesc = grpc.ServiceDesc{
	ServiceName: "social.Social",
	HandlerType: (*SocialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Follow",
			Handler:    _Social_Follow_Handler,
		},
		{
			MethodName: "Unfollow",
			Handler:    _Social_Unfollow_Handler,
		},
		{
			MethodName: "GetFollow",
			Handler:    _Social_GetFollow_Handler,
		},
		{
			MethodName: "GetFollower",
			Handler:    _Social_GetFollower_Handler,
		},
		{
			MethodName: "GetFollowCount",
			Handler:    _Social_GetFollowCount_Handler,
		},
		{
			MethodName: "GetRelations",
			Handler:    _Social_GetRelations_Handler,
		},
		{
			MethodName: "Black",
			Handler:    _Social_Black_Handler,
		},
		{
			MethodName: "CancelBlack",
			Handler:    _Social_CancelBlack_Handler,
		},
		{
			MethodName: "CheckBlack",
			Handler:    _Social_CheckBlack_Handler,
		},
		{
			MethodName: "CheckBatchBlack",
			Handler:    _Social_CheckBatchBlack_Handler,
		},
		{
			MethodName: "GetBlackList",
			Handler:    _Social_GetBlackList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/social/social.proto",
}

func init() { proto.RegisterFile("idl/social/social.proto", fileDescriptor_social_7202e7a91a160a8b) }

var fileDescriptor_social_7202e7a91a160a8b = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0x93, 0x5f, 0xfc, 0x4b, 0xc7, 0x71, 0x53, 0x2d, 0x69, 0x1b, 0x72, 0x21, 0x58, 0x02,
	0x45, 0x1c, 0x8a, 0x94, 0x42, 0xff, 0x8a, 0x03, 0x09, 0x4d, 0x41, 0x42, 0x42, 0x32, 0xea, 0x01,
	0x2e, 0x91, 0xe3, 0x6c, 0xd4, 0x55, 0x1c, 0x6f, 0xf0, 0xae, 0x0b, 0xf9, 0x1c, 0x1c, 0xb8, 0xf1,
	0x59, 0xd1, 0xfe, 0x73, 0x6c, 0x22, 0x0b, 0x82, 0x7a, 0xf2, 0xee, 0xf3, 0x7b, 0x33, 0x6f, 0x67,
	0x66, 0x6d, 0x38, 0x24, 0xd3, 0xe8, 0x39, 0xa3, 0x21, 0x09, 0xcc, 0xe3, 0x68, 0x99, 0x50, 0x4e,
	0x91, 0xad, 0x76, 0xde, 0x29, 0x34, 0x7c, 0x1c, 0x05, 0x9c, 0xd0, 0xf8, 0x1d, 0xc7, 0x0b, 0xb4,
	0x07, 0xd5, 0x94, 0x4c, 0xdb, 0x56, 0xd7, 0xea, 0x55, 0x7d, 0xb1, 0x44, 0xfb, 0x60, 0x73, 0x3a,
	0x16, 0x60, 0x45, 0x82, 0x35, 0x4e, 0x6f, 0xc8, 0xd4, 0x1b, 0x81, 0x3b, 0xa2, 0x51, 0x44, 0xbf,
	0xfa, 0xf8, 0x4b, 0x8a, 0x19, 0x47, 0x2f, 0xc1, 0x99, 0x49, 0x60, 0x4c, 0x38, 0x5e, 0xc8, 0x08,
	0x4e, 0xbf, 0x75, 0xa4, 0xb3, 0xe6, 0x93, 0xf8, 0xa0, 0x88, 0x62, 0xed, 0x35, 0xc1, 0xbd, 0x5a,
	0x2c, 0xf9, 0xca, 0xc7, 0x6c, 0x49, 0x63, 0x86, 0xbd, 0xb7, 0xd0, 0xbc, 0x89, 0x67, 0xf7, 0x11,
	0x7a, 0x08, 0x8d, 0x41, 0x14, 0x84, 0x73, 0x13, 0xe6, 0x18, 0x60, 0x22, 0xf6, 0x7f, 0x8e, 0xb2,
	0x23, 0x79, 0x32, 0xc8, 0x33, 0x70, 0x75, 0x10, 0xe5, 0x0f, 0x3d, 0x84, 0x3a, 0x61, 0x63, 0x49,
	0x90, 0x31, 0xea, 0xfe, 0xff, 0x84, 0x49, 0x8a, 0xf7, 0x01, 0x9c, 0xf7, 0x84, 0x71, 0x93, 0x6f,
	0xb3, 0x96, 0x07, 0x60, 0x87, 0x69, 0xc2, 0x68, 0xa2, 0x6b, 0xa9, 0x77, 0x02, 0xa7, 0xb3, 0x19,
	0xc3, 0xbc, 0x5d, 0x55, 0xb8, 0xda, 0x89, 0x13, 0xa8, 0x80, 0x3a, 0x37, 0x82, 0xff, 0x52, 0x32,
	0x65, 0x6d, 0xab, 0x5b, 0xed, 0x55, 0x7d, 0xb9, 0x46, 0x8f, 0xc0, 0x89, 0xf1, 0x37, 0x3e, 0x2e,
	0x04, 0x06, 0x01, 0x0d, 0x25, 0xe2, 0x75, 0xa1, 0x31, 0xa4, 0x69, 0x5c, 0x6e, 0xcb, 0xfb, 0x04,
	0xae, 0x66, 0xe8, 0x3c, 0x8f, 0xa1, 0xa1, 0x0b, 0x1e, 0x0a, 0x5c, 0x73, 0x75, 0x13, 0x24, 0x15,
	0x3d, 0x81, 0x5d, 0xb5, 0xc5, 0x89, 0x26, 0xa9, 0xcc, 0xae, 0x41, 0x25, 0xcd, 0x3b, 0x85, 0xa6,
	0xa9, 0x6c, 0x79, 0x59, 0xcc, 0xb1, 0x2a, 0xeb, 0x63, 0x79, 0xdf, 0x2d, 0xd8, 0x5b, 0x2b, 0xb5,
	0xaf, 0x01, 0xd4, 0x13, 0x8d, 0xc9, 0x1a, 0x38, 0xfd, 0xa7, 0xbf, 0xf7, 0xcf, 0x70, 0x33, 0xe0,
	0x2a, 0xe6, 0xc9, 0xca, 0xcf, 0x74, 0x9d, 0x4b, 0x70, 0x0b, 0xaf, 0x84, 0x9f, 0x39, 0x5e, 0x19,
	0x3f, 0x73, 0xbc, 0x42, 0x2d, 0xa8, 0xdd, 0x05, 0x51, 0x8a, 0xe5, 0x91, 0x6a, 0xbe, 0xda, 0x5c,
	0x54, 0xce, 0x2c, 0xef, 0x87, 0x05, 0x48, 0xf6, 0x7a, 0x10, 0xf0, 0xf0, 0x36, 0xf3, 0xf5, 0x66,
	0xc3, 0x57, 0xcf, 0xf8, 0xda, 0x64, 0xdf, 0x9b, 0xb3, 0x7a, 0xce, 0x59, 0xff, 0x67, 0x0d, 0xec,
	0x8f, 0x32, 0x25, 0x3a, 0x01, 0x5b, 0x5d, 0x4d, 0xb4, 0x6f, 0x5c, 0x14, 0xae, 0x6a, 0x27, 0x83,
	0x0b, 0x37, 0x0f, 0x9d, 0x41, 0xdd, 0xdc, 0xbc, 0x2d, 0x95, 0x27, 0xb0, 0x73, 0x8d, 0xb9, 0x4e,
	0xfa, 0xc0, 0x70, 0x72, 0x77, 0xa1, 0xd3, 0x2a, 0x82, 0x59, 0x46, 0x27, 0xd3, 0xe1, 0x64, 0x1b,
	0xe5, 0x2b, 0xd8, 0xcd, 0x94, 0x6a, 0x20, 0x33, 0x5e, 0x7e, 0xd8, 0xd7, 0x86, 0x8b, 0x03, 0xfe,
	0x1a, 0x1a, 0xd7, 0x98, 0x9b, 0x6a, 0x33, 0x74, 0xb8, 0x39, 0x46, 0x4a, 0xdf, 0x2e, 0x9b, 0x2f,
	0xf4, 0x02, 0x6a, 0xb2, 0xb7, 0xeb, 0xc4, 0xf9, 0x8f, 0x4d, 0x59, 0xa5, 0x2e, 0xc0, 0x19, 0x06,
	0x71, 0x88, 0xa3, 0x7f, 0xd0, 0x9e, 0x03, 0x0c, 0x6f, 0x71, 0x38, 0xff, 0x2b, 0x69, 0xf1, 0xa3,
	0x35, 0x82, 0xa6, 0x92, 0x8a, 0x41, 0x54, 0xfa, 0xd2, 0x23, 0x77, 0xca, 0x47, 0x17, 0x9d, 0xcb,
	0xba, 0xc9, 0x17, 0xa2, 0x1d, 0x5b, 0x74, 0x6c, 0x70, 0xf0, 0xb9, 0xb5, 0x9c, 0xe8, 0x9f, 0xd0,
	0xa5, 0x7a, 0x8c, 0xd9, 0x5d, 0x38, 0xb1, 0xe5, 0x0f, 0xe9, 0xf8, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xee, 0xfe, 0xe8, 0xcc, 0xab, 0x06, 0x00, 0x00,
}
